version: '2'
services:
  web:
    build: .
    command: npm run start:dev
    container_name: lear_dev
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres@postgres/lear_dev
  postgres:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: lear